name: Android build

on: push

env:
    GODOT_VERSION: 4.2.1
    WORKING_DIRECTORY: .

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout source code
              uses: actions/checkout@v3

            - name: Read version number and version code
              run: |
                echo "VERSION_NAME=$(cat version | cut -f1 -d-)" >> $GITHUB_ENV
                echo "VERSION_CODE=$(cat version | cut -f2 -d-)" >> $GITHUB_ENV

            - name: Create export_presets.cfg and inject values
              run: |
                cp $WORKING_DIRECTORY/export_presets.android.example $WORKING_DIRECTORY/export_presets.cfg
                sed -i "s|VERSION_CODE|$VERSION_CODE|g" $WORKING_DIRECTORY/export_presets.cfg
                sed -i "s|VERSION_NAME|$VERSION_NAME|g" $WORKING_DIRECTORY/export_presets.cfg
                mkdir -p .godot/editor
                mkdir -p .godot/imported

            - name: Godot Android export
              uses: Jokymon/godot-android-export@v4.0.4
              with:
                working-directory: $WORKING_DIRECTORY
                godot-version: ${{ env.GODOT_VERSION }}

            - name: Bundle aab to apk
              run: |
                wget -q https://github.com/google/bundletool/releases/download/1.14.0/bundletool-all-1.14.0.jar
                java -jar bundletool-all-1.14.0.jar build-apks --bundle=AstroShoot.aab --output=AstroShoot.apks \
                --mode=universal
                unzip -p AstroShoot.apks universal.apk > AstroShoot.apk

            - name: Upload binaries to Github release
              uses: svenstaro/upload-release-action@v2
              with:
                repo_token: ${{ secrets.GITHUB_TOKEN }}
                file: ./AstroShoot.apk
                asset_name: AstroShoot.apk
                overwrite: true
